### ISSUE TITLE
'git submodule update --init --recursive' error

### ISSUE THREAD

**Issue by AGhiuta** [soumith/torch-android#37]
Hi,

I get the following errors when running git submodule update --init --recursive

Cloning into 'extra/cudnn'...
remote: Counting objects: 1184, done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 1184 (delta 76), reused 0 (delta 0), pack-reused 1044
Receiving objects: 100% (1184/1184), 453.90 KiB | 479.00 KiB/s, done.
Resolving deltas: 100% (753/753), done.
Checking connectivity... done.
fatal: reference is not a tree: 8f4c536c0cd0e753d45f42e5ccd9f7052b4690da

Failed to recurse into submodule path 'distro'

Help much appreciated

**Comment by borisfom** [comment]
Should be fixed now, please confirm!

**Comment by AGhiuta** [comment]
The problem still persists. Moreover,  i get

 Submodule path 'distro/pkg/xlua': checked out '98c11caac263e21f793ab2e6a8ed536b3c7cb135'
Unable to checkout 'fb0b256c3b98904f85e7f02288f78654c39350c3' in submodule path 'distro/extra/cunn'
Unable to checkout 'd21ddb2a85ccaf393ba2a8410637a354ed8e87b5' in submodule path 'distro/extra/cutorch'
