### ISSUE TITLE
Failed to recurse into submodule path 'distro'

### ISSUE THREAD

**Issue by huanggengxin** [soumith/torch-android#56]
ill@Will-Air ~/torch/torch-android $ git submodule update --init --recursive
Submodule 'distro' (https://github.com/borisfom/distro) registered for path 'distro'
Submodule 'external/libjpeg-turbo' (https://github.com/libjpeg-turbo/libjpeg-turbo) registered for path 'external/libjpeg-turbo'
Submodule 'external/libpng' (https://github.com/borisfom/platform_external_libpng) registered for path 'external/libpng'
Cloning into 'distro'...
remote: Counting objects: 3069, done.
Receiving objects:  65% (2007/3069), 101.14 MiB | 68.00 KiB/s  
remote: Total 3069 (delta 0), reused 0 (delta 0), pack-reused 3069
Receiving objects: 100% (3069/3069), 374.95 MiB | 80.00 KiB/s, done.
Resolving deltas: 100% (1658/1658), done.
Checking connectivity... done.
Submodule path 'distro': checked out '37094cff2243281e504186daf14ba331739e7301'
Submodule 'exe/env' (https://github.com/torch/env.git) registered for path 'exe/env'
Submodule 'exe/luajit-rocks' (https://github.com/torch/luajit-rocks.git) registered for path 'exe/luajit-rocks'
Submodule 'exe/qtlua' (https://github.com/torch/qtlua.git) registered for path 'exe/qtlua'
Submodule 'exe/trepl' (https://github.com/torch/trepl.git) registered for path 'exe/trepl'
Submodule 'extra/FindCUDA' (https://github.com/borisfom/FindCUDA.git) registered for path 'extra/FindCUDA'
Submodule 'extra/argcheck' (https://github.com/torch/argcheck.git) registered for path 'extra/argcheck'
Submodule 'extra/audio' (https://github.com/soumith/lua---audio.git) registered for path 'extra/audio'
Submodule 'extra/cudnn' (https://github.com/borisfom/cudnn.torch.git) registered for path 'extra/cudnn'
Submodule 'extra/cunn' (https://github.com/borisfom/cunn.git) registered for path 'extra/cunn'
Submodule 'extra/cunnx' (https://github.com/borisfom/cunnx.git) registered for path 'extra/cunnx'
Submodule 'extra/cutorch' (https://github.com/borisfom/cutorch.git) registered for path 'extra/cutorch'
Submodule 'extra/fftw3' (https://github.com/soumith/fftw3-ffi.git) registered for path 'extra/fftw3'
Submodule 'extra/graph' (https://github.com/torch/graph) registered for path 'extra/graph'
Submodule 'extra/graphicsmagick' (https://github.com/clementfarabet/graphicsmagick.git) registered for path 'extra/graphicsmagick'
Submodule 'extra/hdf5' (https://github.com/deepmind/torch-hdf5.git) registered for path 'extra/hdf5'
Submodule 'extra/lmdb' (https://github.com/LuaDist2/lightningmdb.git) registered for path 'extra/lmdb'
Submodule 'extra/lua-cjson' (https://github.com/mpx/lua-cjson) registered for path 'extra/lua-cjson'
Submodule 'extra/lua-pb' (https://github.com/Neopallium/lua-pb.git) registered for path 'extra/lua-pb'
Submodule 'extra/luaffifb' (https://github.com/facebook/luaffifb) registered for path 'extra/luaffifb'
Submodule 'extra/luafilesystem' (https://github.com/keplerproject/luafilesystem.git) registered for path 'extra/luafilesystem'
Submodule 'extra/nccl' (https://github.com/ngimel/nccl.torch.git) registered for path 'extra/nccl'
Submodule 'extra/nn' (https://github.com/torch/nn.git) registered for path 'extra/nn'
Submodule 'extra/nngraph' (https://github.com/torch/nngraph) registered for path 'extra/nngraph'
Submodule 'extra/nnx' (https://github.com/clementfarabet/lua---nnx.git) registered for path 'extra/nnx'
Submodule 'extra/penlight' (https://github.com/stevedonovan/Penlight.git) registered for path 'extra/penlight'
Submodule 'extra/sdl2' (https://github.com/torch/sdl2-ffi.git) registered for path 'extra/sdl2'
Submodule 'extra/signal' (https://github.com/soumith/torch-signal.git) registered for path 'extra/signal'
Submodule 'extra/tds' (https://github.com/torch/tds.git) registered for path 'extra/tds'
Submodule 'extra/threads' (https://github.com/torch/threads-ffi.git) registered for path 'extra/threads'
Submodule 'extra/totem' (https://github.com/deepmind/torch-totem.git) registered for path 'extra/totem'
Submodule 'pkg/cwrap' (https://github.com/torch/cwrap.git) registered for path 'pkg/cwrap'
Submodule 'pkg/dok' (https://github.com/torch/dok.git) registered for path 'pkg/dok'
Submodule 'pkg/gnuplot' (https://github.com/torch/gnuplot.git) registered for path 'pkg/gnuplot'
Submodule 'pkg/image' (https://github.com/torch/image.git) registered for path 'pkg/image'
Submodule 'pkg/optim' (https://github.com/torch/optim.git) registered for path 'pkg/optim'
Submodule 'pkg/paths' (https://github.com/torch/paths.git) registered for path 'pkg/paths'
Submodule 'pkg/qttorch' (https://github.com/torch/qttorch.git) registered for path 'pkg/qttorch'
Submodule 'pkg/sundown' (https://github.com/torch/sundown-ffi.git) registered for path 'pkg/sundown'
Submodule 'pkg/sys' (https://github.com/torch/sys.git) registered for path 'pkg/sys'
Submodule 'pkg/torch' (https://github.com/torch/torch7.git) registered for path 'pkg/torch'
Submodule 'pkg/xlua' (https://github.com/torch/xlua.git) registered for path 'pkg/xlua'
Cloning into 'exe/env'...
remote: Counting objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
Submodule path 'distro/exe/env': checked out '40d6fa037e52dca9eab161ab8f1e5496a52c3c1e'
Cloning into 'exe/luajit-rocks'...
remote: Counting objects: 2323, done.
remote: Total 2323 (delta 0), reused 0 (delta 0), pack-reused 2323
Receiving objects: 100% (2323/2323), 7.31 MiB | 13.00 KiB/s, done.
Resolving deltas: 100% (1368/1368), done.
Checking connectivity... done.
Submodule path 'distro/exe/luajit-rocks': checked out '3a64814592231e6557f4cacbd2e42cd0caec7939'
Cloning into 'exe/qtlua'...
remote: Counting objects: 664, done.
remote: Total 664 (delta 0), reused 0 (delta 0), pack-reused 664
Receiving objects: 100% (664/664), 582.16 KiB | 155.00 KiB/s, done.
Resolving deltas: 100% (326/326), done.
Checking connectivity... done.
Submodule path 'distro/exe/qtlua': checked out 'c077ce7b429a1e4d9fc8c96dd7115b06ea8bbe46'
Cloning into 'exe/trepl'...
remote: Counting objects: 469, done.
remote: Total 469 (delta 0), reused 0 (delta 0), pack-reused 469
Receiving objects: 100% (469/469), 108.10 KiB | 77.00 KiB/s, done.
Resolving deltas: 100% (270/270), done.
Checking connectivity... done.
Submodule path 'distro/exe/trepl': checked out 'f2d2f1ad40d5dc695d75c4ef2edd36142d319e49'
Cloning into 'extra/FindCUDA'...
remote: Counting objects: 106, done.
remote: Total 106 (delta 0), reused 0 (delta 0), pack-reused 106
Receiving objects: 100% (106/106), 49.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (54/54), done.
Checking connectivity... done.
Submodule path 'distro/extra/FindCUDA': checked out 'fa75fcfa61271c1c0ba9c5a46dff9b63b2ad359d'
Cloning into 'extra/argcheck'...
remote: Counting objects: 534, done.
remote: Total 534 (delta 0), reused 0 (delta 0), pack-reused 534
Receiving objects: 100% (534/534), 645.32 KiB | 52.00 KiB/s, done.
Resolving deltas: 100% (289/289), done.
Checking connectivity... done.
Submodule path 'distro/extra/argcheck': checked out '1781cd574bddd39fdad3b3833db510d3b8b1474f'
Cloning into 'extra/audio'...
remote: Counting objects: 221, done.
remote: Total 221 (delta 0), reused 0 (delta 0), pack-reused 221
Receiving objects: 100% (221/221), 187.93 KiB | 130.00 KiB/s, done.
Resolving deltas: 100% (114/114), done.
Checking connectivity... done.
Submodule path 'distro/extra/audio': checked out 'e71fce7f248be8a4937a1de76dae0883fe4fc454'
Cloning into 'extra/cudnn'...
remote: Counting objects: 1441, done.
remote: Total 1441 (delta 0), reused 0 (delta 0), pack-reused 1441
Receiving objects: 100% (1441/1441), 507.85 KiB | 223.00 KiB/s, done.
Resolving deltas: 100% (918/918), done.
Checking connectivity... done.
Submodule path 'distro/extra/cudnn': checked out '6c608bef57da039813f759efc6f9b6caa5c7389b'
Cloning into 'extra/cunn'...
remote: Counting objects: 1896, done.
remote: Total 1896 (delta 0), reused 0 (delta 0), pack-reused 1896
Receiving objects: 100% (1896/1896), 810.74 KiB | 329.00 KiB/s, done.
Resolving deltas: 100% (1128/1128), done.
Checking connectivity... done.
fatal: reference is not a tree: 0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a
Cloning into 'extra/cunnx'...
remote: Counting objects: 816, done.
remote: Total 816 (delta 0), reused 0 (delta 0), pack-reused 816
Receiving objects: 100% (816/816), 196.60 KiB | 126.00 KiB/s, done.
Resolving deltas: 100% (529/529), done.
Checking connectivity... done.
Submodule path 'distro/extra/cunnx': checked out '711072d58b0aa997de8ed08f43a66aff89ae22ff'
Cloning into 'extra/cutorch'...
remote: Counting objects: 2875, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2875 (delta 0), reused 0 (delta 0), pack-reused 2870
Receiving objects: 100% (2875/2875), 10.38 MiB | 384.00 KiB/s, done.
Resolving deltas: 100% (1585/1585), done.
Checking connectivity... done.
fatal: reference is not a tree: 43a5dfacfc310aab31f81654cd1b143ad9ec2b1c
Cloning into 'extra/fftw3'...
remote: Counting objects: 98, done.
remote: Total 98 (delta 0), reused 0 (delta 0), pack-reused 98
Unpacking objects: 100% (98/98), done.
Checking connectivity... done.
Submodule path 'distro/extra/fftw3': checked out 'ce8883364201b0741d3d51a0f305f457778a6671'
Cloning into 'extra/graph'...
remote: Counting objects: 208, done.
remote: Total 208 (delta 0), reused 0 (delta 0), pack-reused 208
Receiving objects: 100% (208/208), 52.94 KiB | 8.00 KiB/s, done.
Resolving deltas: 100% (104/104), done.
Checking connectivity... done.
Submodule path 'distro/extra/graph': checked out '34d712890badbb9f9d05a46d073ff1d91af0f6ee'
Cloning into 'extra/graphicsmagick'...
remote: Counting objects: 358, done.
remote: Total 358 (delta 0), reused 0 (delta 0), pack-reused 358
Receiving objects: 100% (358/358), 855.98 KiB | 6.00 KiB/s, done.
Resolving deltas: 100% (187/187), done.
Checking connectivity... done.
Submodule path 'distro/extra/graphicsmagick': checked out '7839f35b4edb099d5c362e63e9ad78f3718ba861'
Cloning into 'extra/hdf5'...
remote: Counting objects: 690, done.
remote: Total 690 (delta 0), reused 0 (delta 0), pack-reused 690
Receiving objects: 100% (690/690), 228.60 KiB | 4.00 KiB/s, done.
Resolving deltas: 100% (408/408), done.
Checking connectivity... done.
Submodule path 'distro/extra/hdf5': checked out 'f364b442655b0fe21dafe83104f42c3bb7b2a594'
Cloning into 'extra/lmdb'...
remote: Counting objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), done.
Checking connectivity... done.
Submodule path 'distro/extra/lmdb': checked out 'fc077a66ebaf309b0b8cb805b60514334f81f628'
Cloning into 'extra/lua-cjson'...
remote: Counting objects: 1001, done.
remote: Total 1001 (delta 0), reused 0 (delta 0), pack-reused 1001
Receiving objects: 100% (1001/1001), 267.98 KiB | 49.00 KiB/s, done.
Resolving deltas: 100% (635/635), done.
Checking connectivity... done.
Submodule path 'distro/extra/lua-cjson': checked out '7eb09593cbddfa682f81f198734ce508b519fe00'
Cloning into 'extra/lua-pb'...
remote: Counting objects: 735, done.
remote: Total 735 (delta 0), reused 0 (delta 0), pack-reused 735
Receiving objects: 100% (735/735), 165.61 KiB | 44.00 KiB/s, done.
Resolving deltas: 100% (438/438), done.
Checking connectivity... done.
Submodule path 'distro/extra/lua-pb': checked out 'ab3755cc093ca1b6f8bf2a9294d9ee30703bc518'
Cloning into 'extra/luaffifb'...
remote: Counting objects: 928, done.
remote: Total 928 (delta 0), reused 0 (delta 0), pack-reused 928
Receiving objects: 100% (928/928), 440.08 KiB | 77.00 KiB/s, done.
Resolving deltas: 100% (656/656), done.
Checking connectivity... done.
Submodule path 'distro/extra/luaffifb': checked out 'ecdd2b1b5aad9d2087de00cdb27b385031d7f2c0'
Cloning into 'extra/luafilesystem'...
remote: Counting objects: 1496, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1496 (delta 0), reused 0 (delta 0), pack-reused 1492
Receiving objects: 100% (1496/1496), 276.38 KiB | 29.00 KiB/s, done.
Resolving deltas: 100% (669/669), done.
Checking connectivity... done.
Submodule path 'distro/extra/luafilesystem': checked out '436bc441fa34a086adfae776941e6e7c111a4582'
Cloning into 'extra/nccl'...
remote: Counting objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), done.
Checking connectivity... done.
Submodule path 'distro/extra/nccl': checked out '0e8e8b140a22b8bdab8402d9cec5522a4962381f'
Cloning into 'extra/nn'...
remote: Counting objects: 5624, done.
remote: Total 5624 (delta 0), reused 0 (delta 0), pack-reused 5623
Receiving objects: 100% (5624/5624), 2.54 MiB | 24.00 KiB/s, done.
Resolving deltas: 100% (3605/3605), done.
Checking connectivity... done.
Submodule path 'distro/extra/nn': checked out 'c8806b80ee211ce70c612addecebf236abdf8734'
Cloning into 'extra/nngraph'...
remote: Counting objects: 634, done.
remote: Total 634 (delta 0), reused 0 (delta 0), pack-reused 633
Receiving objects: 100% (634/634), 1.85 MiB | 288.00 KiB/s, done.
Resolving deltas: 100% (338/338), done.
Checking connectivity... done.
Submodule path 'distro/extra/nngraph': checked out 'd0c239bdcfcd01d0ce77127136d20fc93767c1bf'
Cloning into 'extra/nnx'...
remote: Counting objects: 2454, done.
remote: Total 2454 (delta 0), reused 0 (delta 0), pack-reused 2454
Receiving objects: 100% (2454/2454), 1.26 MiB | 63.00 KiB/s, done.
Resolving deltas: 100% (1406/1406), done.
Checking connectivity... done.
Submodule path 'distro/extra/nnx': checked out '6283ef3d9fed244422788d0329998a485e4f2a75'
Cloning into 'extra/penlight'...
remote: Counting objects: 3380, done.
remote: Total 3380 (delta 0), reused 0 (delta 0), pack-reused 3380
Receiving objects: 100% (3380/3380), 1.29 MiB | 218.00 KiB/s, done.
Resolving deltas: 100% (2003/2003), done.
Checking connectivity... done.
Submodule path 'distro/extra/penlight': checked out '16d149338af9efc910528641c5240c5641aeb8db'
Cloning into 'extra/sdl2'...
remote: Counting objects: 74, done.
remote: Total 74 (delta 0), reused 0 (delta 0), pack-reused 74
Unpacking objects: 100% (74/74), done.
Checking connectivity... done.
Submodule path 'distro/extra/sdl2': checked out '50659fbeca83d667240b197298a0462c7ec0ad21'
Cloning into 'extra/signal'...
remote: Counting objects: 437, done.
remote: Total 437 (delta 0), reused 0 (delta 0), pack-reused 437
Receiving objects: 100% (437/437), 137.87 KiB | 53.00 KiB/s, done.
Resolving deltas: 100% (202/202), done.
Checking connectivity... done.
Submodule path 'distro/extra/signal': checked out '94290c5297c25aaf76e93a1a9ff050da600af1df'
Cloning into 'extra/tds'...
remote: Counting objects: 509, done.
remote: Total 509 (delta 0), reused 0 (delta 0), pack-reused 509
Receiving objects: 100% (509/509), 632.97 KiB | 16.00 KiB/s, done.
Resolving deltas: 100% (272/272), done.
Checking connectivity... done.
Submodule path 'distro/extra/tds': checked out '5382691f13d69cc48df373e1821c1579abf26d4a'
Cloning into 'extra/threads'...
remote: Counting objects: 361, done.
remote: Total 361 (delta 0), reused 0 (delta 0), pack-reused 361
Receiving objects: 100% (361/361), 93.66 KiB | 36.00 KiB/s, done.
Resolving deltas: 100% (192/192), done.
Checking connectivity... done.
Submodule path 'distro/extra/threads': checked out '628ab68498f4e3095709ee60a1bbd83cc4f0b556'
Cloning into 'extra/totem'...
remote: Counting objects: 618, done.
remote: Total 618 (delta 0), reused 0 (delta 0), pack-reused 618
Receiving objects: 100% (618/618), 170.70 KiB | 13.00 KiB/s, done.
Resolving deltas: 100% (312/312), done.
Checking connectivity... done.
Submodule path 'distro/extra/totem': checked out '21240faf12ee7db95d7adc41760a04ec4ca036d0'
Cloning into 'pkg/cwrap'...
remote: Counting objects: 109, done.
remote: Total 109 (delta 0), reused 0 (delta 0), pack-reused 109
Receiving objects: 100% (109/109), 37.91 KiB | 14.00 KiB/s, done.
Resolving deltas: 100% (43/43), done.
Checking connectivity... done.
Submodule path 'distro/pkg/cwrap': checked out 'dbd0a623dc4dfb4b8169d5aecc6dd9aec2f22792'
Cloning into 'pkg/dok'...
remote: Counting objects: 186, done.
remote: Total 186 (delta 0), reused 0 (delta 0), pack-reused 186
Receiving objects: 100% (186/186), 149.67 KiB | 68.00 KiB/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
Submodule path 'distro/pkg/dok': checked out '1b36900e1bfa6ee7f48db52c577bdeb7d9e85909'
Cloning into 'pkg/gnuplot'...
remote: Counting objects: 297, done.
remote: Total 297 (delta 0), reused 0 (delta 0), pack-reused 297
Receiving objects: 100% (297/297), 224.83 KiB | 131.00 KiB/s, done.
Resolving deltas: 100% (161/161), done.
Checking connectivity... done.
Submodule path 'distro/pkg/gnuplot': checked out '1955fb2fdf6dcdc5241727d09a838987700cb715'
Cloning into 'pkg/image'...
remote: Counting objects: 1289, done.
remote: Total 1289 (delta 0), reused 0 (delta 0), pack-reused 1289
Receiving objects: 100% (1289/1289), 2.19 MiB | 240.00 KiB/s, done.
Resolving deltas: 100% (706/706), done.
Checking connectivity... done.
Submodule path 'distro/pkg/image': checked out '0680e1fc7b99c0d6aaebc2985aa4df18f082c1b9'
Cloning into 'pkg/optim'...
remote: Counting objects: 798, done.
remote: Total 798 (delta 0), reused 0 (delta 0), pack-reused 798
Receiving objects: 100% (798/798), 186.69 KiB | 100.00 KiB/s, done.
Resolving deltas: 100% (443/443), done.
Checking connectivity... done.
Submodule path 'distro/pkg/optim': checked out '177492ab0abaa08cdcf3f1f1c0a3b138fe5870b2'
Cloning into 'pkg/paths'...
remote: Counting objects: 145, done.
remote: Total 145 (delta 0), reused 0 (delta 0), pack-reused 145
Receiving objects: 100% (145/145), 52.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
Submodule path 'distro/pkg/paths': checked out '68d579a2d3b1b0bb03a11637632e6e699b14ad80'
Cloning into 'pkg/qttorch'...
remote: Counting objects: 60, done.
remote: Total 60 (delta 0), reused 0 (delta 0), pack-reused 60
Unpacking objects: 100% (60/60), done.
Checking connectivity... done.
Submodule path 'distro/pkg/qttorch': checked out 'ba5b5a143482857f80237181d5fde0a3ba20477b'
Cloning into 'pkg/sundown'...
remote: Counting objects: 217, done.
remote: Total 217 (delta 0), reused 0 (delta 0), pack-reused 217
Receiving objects: 100% (217/217), 135.26 KiB | 128.00 KiB/s, done.
Resolving deltas: 100% (65/65), done.
Checking connectivity... done.
Submodule path 'distro/pkg/sundown': checked out 'ab92c0c0ed7312361bede8c138fb4eb9b08ce363'
Cloning into 'pkg/sys'...
remote: Counting objects: 199, done.
remote: Total 199 (delta 0), reused 0 (delta 0), pack-reused 199
Receiving objects: 100% (199/199), 31.37 KiB | 0 bytes/s, done.
Resolving deltas: 100% (104/104), done.
Checking connectivity... done.
Submodule path 'distro/pkg/sys': checked out '8d2b8facd22e55d66ac71cb778f451694e7611fa'
Cloning into 'pkg/torch'...
remote: Counting objects: 4756, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 4756 (delta 0), reused 0 (delta 0), pack-reused 4751
Receiving objects: 100% (4756/4756), 1.75 MiB | 771.00 KiB/s, done.
Resolving deltas: 100% (2997/2997), done.
Checking connectivity... done.
Submodule path 'distro/pkg/torch': checked out '1246c8935eff6b2cc61441de479173b90a4c25e7'
Cloning into 'pkg/xlua'...
remote: Counting objects: 276, done.
remote: Total 276 (delta 0), reused 0 (delta 0), pack-reused 276
Receiving objects: 100% (276/276), 58.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (154/154), done.
Checking connectivity... done.
Submodule path 'distro/pkg/xlua': checked out '98c11caac263e21f793ab2e6a8ed536b3c7cb135'
Unable to checkout '0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a' in submodule path 'distro/extra/cunn'
Unable to checkout '43a5dfacfc310aab31f81654cd1b143ad9ec2b1c' in submodule path 'distro/extra/cutorch'
Cloning into 'external/libjpeg-turbo'...
remote: Counting objects: 11056, done.
remote: Total 11056 (delta 0), reused 0 (delta 0), pack-reused 11056
Receiving objects: 100% (11056/11056), 9.50 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (8124/8124), done.
Checking connectivity... done.
Submodule path 'external/libjpeg-turbo': checked out '2e480fa2a3285d9ff83a780ab3417badeb3f2d37'
Cloning into 'external/libpng'...
remote: Counting objects: 1789, done.
remote: Total 1789 (delta 0), reused 0 (delta 0), pack-reused 1789
Receiving objects: 100% (1789/1789), 2.96 MiB | 175.00 KiB/s, done.
Resolving deltas: 100% (961/961), done.
Checking connectivity... done.
Submodule path 'external/libpng': checked out '2964a877aeeb02a66eeba084ceb1dfa3c6836f1b'
Failed to recurse into submodule path 'distro'

**Comment by huanggengxin** [comment]
How cloud I fix it?

**Comment by huanggengxin** [comment]
who can help me ?

**Comment by borisfom** [comment]
Should be fixed now - please check out to a fresh workspace.

**Comment by huanggengxin** [comment]
Sorry ,I think the problem is still exist.
Please confirm the issue.

**Comment by huanggengxin** [comment]
Thank you !
The problem was sloved.

**Comment by PoorvajaBhaskaran** [comment]
Even i got the same issue any one can help me..
 git submodule update --init --recursive

Cloning into 'riscv-glibc'...
remote: Counting objects: 401518, done.
remote: Total 401518 (delta 0), reused 0 (delta 0), pack-reused 401518
Receiving objects: 100% (401518/401518), 123.95 MiB | 515.00 KiB/s, done.
Resolving deltas: 100% (338610/338610), done.
fatal: object of unexpected type
fatal: index-pack failed
Clone of 'https://github.com/riscv/riscv-glibc.git' into submodule path 'riscv-glibc' failed
Failed to recurse into submodule path 'riscv-gnu-toolchain'
