### ISSUE TITLE
libjpeg and libpng not working

### ISSUE THREAD

**Issue by czhang96** [soumith/torch-android#64]
Why is there no support for libjpeg-turbo? I see it is commented out in the `build.sh`. How can I build/use libjpeg-turbo. I get the following when trying to load a jpg: 

`<libjpeg> could not be loaded (is it installed?)
Error doing resource: main.lua:[string "dok/inline"]:738: [1;31m<image.loadJPG> libjpeg package not found, please install libjpeg[0m`

Additionally, when I try to load a png, I get the following

 `error loading module 'libpng' from file '/data/app/com.torch.torchdemo-2/lib/arm/libpng.so': undefined symbol: luaopen_libpng
warning: <libpng> could not be loaded (is it installed?)
 Error doing resource: main.lua:[string "dok/inline"]:738: [1;31m<image.loadPNG> libpng package not found, please install libpng[0m`

I've confirmed that `libpng.so` is in `/data/app/com.torch.torchdemo-2/lib/arm/` (but `libjpeg` is not).
I have run `build.sh` in the root folder succesfully. Please help me

**Comment by borisfom** [comment]
I was not able to build jpeg correctly :(. If you can help, we'll appreciate that!

**Comment by borisfom** [comment]
Re libpng: try to load it explicitly via LoadLibrary

**Comment by zhouyong64** [comment]
I have the same issue. Loading "libpng" via LoadLibrary causes the following error:
java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libpng16.so.16" needed by "libtorchdemo.so"; caused by library "libpng16.so.16 not found

I have copied libpng16.so.16.20.0 and renamed it to libpng16.so.16 and placed it under armeabi-v7a, but still get the error.

**Comment by borisfom** [comment]
Libpng issue is solved. Libjpeg needs to be ported.

**Comment by wartstone** [comment]
Hi there, I still cannot get libpng & libjpeg through. Tried one week already...   Error is always "error loading module 'libpng' from file '/data/app/**/lib/arm/libpng.so':undefined symbol: luaopen_libpng".  I build with "./build.sh". && update my NDK version from 12b to 13b now. Any help would be appreciated. Thanks in advance.
