### ISSUE TITLE
git submodule update --init --recursive is not able to clone FindCUDA

### ISSUE THREAD

**Issue by viralparekh** [soumith/torch-android#74]
Repo https://github.com/borisfom/FindCUDA.git  does not exist or it is private repo, thus
`git submodule update --init --recursive` is not able to clone FindCUDA

**Comment by viralparekh** [comment]
@borisfom  can you let me know how can I include FindCuda package in order to complete the build successfully.

Thank you.

**Comment by BrianOn99** [comment]
Same issue here.  Even worse, after commit 4db8f11, there is no submodule for FindCUDA anymore, but build.sh line 113 needs that.

**Comment by borisfom** [comment]
@BrianOn99 : Please use https://NVIDIA/torch-android.git in the meantime.

**Comment by Erhannis** [comment]
I, too, have this issue.  I'm pretty sure https://NVIDIA/torch-android.git is not a valid URL, yeah?

If I comment out the part of build.sh that references FindCUDA, (also, I've set WITH_CUDA=OFF), then it starts to build, but I get error messages (which I think are kinda scrambled, maybe).

One of them resembles the soname error mentioned in https://github.com/soumith/torch-android/issues/34 and the other is `impossible constraint in 'asm'`

```
erhannis@mnode6:~/projects/torch-android$ ./build.sh
Android NDK found at: /home/erhannis/Android/Sdk/ndk-bundle/
INSTALL_DIR=/home/erhannis/projects/torch-android/install
CMake Deprecation Warning at /usr/local/share/cmake-3.5/Modules/CMakeForceCompiler.cmake:73 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/erhannis/projects/torch-android/cmake/android.toolchain.cmake:1128 (CMAKE_FORCE_C_COMPILER)
  build/CMakeFiles/3.5.0-rc1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:14 (project)


CMake Deprecation Warning at /usr/local/share/cmake-3.5/Modules/CMakeForceCompiler.cmake:87 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/erhannis/projects/torch-android/cmake/android.toolchain.cmake:1140 (CMAKE_FORCE_CXX_COMPILER)
  build/CMakeFiles/3.5.0-rc1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:14 (project)


CMake Warning (dev) at CMakeLists.txt:311 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:320 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/erhannis/projects/torch-android/external/libpng/build
 -------------- Configuring DONE ---------------
/usr/local/bin/cmake -H/home/erhannis/projects/torch-android/external/libpng -B/home/erhannis/projects/torch-android/external/libpng/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
cd /home/erhannis/projects/torch-android/external/libpng/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/png16.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[2]: Nothing to be done for 'CMakeFiles/png16.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
[ 42%] Built target png16
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
cd /home/erhannis/projects/torch-android/external/libpng/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/png16_static.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[2]: Nothing to be done for 'CMakeFiles/png16_static.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
[ 85%] Built target png16_static
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
cd /home/erhannis/projects/torch-android/external/libpng/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/pngtest.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[2]: Nothing to be done for 'CMakeFiles/pngtest.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
[ 90%] Built target pngtest
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
cd /home/erhannis/projects/torch-android/external/libpng/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/pngstest.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[2]: Nothing to be done for 'CMakeFiles/pngstest.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
[ 95%] Built target pngstest
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
cd /home/erhannis/projects/torch-android/external/libpng/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles/pngvalid.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[2]: Nothing to be done for 'CMakeFiles/pngvalid.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
[100%] Built target pngvalid
make[1]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
/usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/external/libpng/build/CMakeFiles 0
make -f CMakeFiles/Makefile2 preinstall
make[1]: Entering directory '/home/erhannis/projects/torch-android/external/libpng/build'
make[1]: Nothing to be done for 'preinstall'.
make[1]: Leaving directory '/home/erhannis/projects/torch-android/external/libpng/build'
Install the project...
/usr/local/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libpng16.so
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libpng16.a
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libpng.so
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libpng.a
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/png.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/pngconf.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/pnglibconf.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/libpng16/png.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/libpng16/pngconf.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/libpng16/pnglibconf.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/bin/libpng-config
-- Up-to-date: /home/erhannis/projects/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/man/man3/libpng.3
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/man/man3/libpngpf.3
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/man/man5/png.5
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/pkgconfig/libpng.pc
-- Up-to-date: /home/erhannis/projects/torch-android/install/bin/libpng-config
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/pkgconfig/libpng16.pc
-- Up-to-date: /home/erhannis/projects/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libpng/libpng16.cmake
-- Installing: /home/erhannis/projects/torch-android/install/lib/libpng/libpng16-noconfig.cmake
libpng installed
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[1]: Entering directory '/home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
==== Successfully built LuaJIT 2.1.0-beta1 ====
Done installing Lua
CMake Deprecation Warning at /usr/local/share/cmake-3.5/Modules/CMakeForceCompiler.cmake:73 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/android.toolchain.cmake:1128 (CMAKE_FORCE_C_COMPILER)
  build/CMakeFiles/3.5.0-rc1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt


CMake Deprecation Warning at /usr/local/share/cmake-3.5/Modules/CMakeForceCompiler.cmake:87 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/android.toolchain.cmake:1140 (CMAKE_FORCE_CXX_COMPILER)
  build/CMakeFiles/3.5.0-rc1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt


-- LuaJIT Target: arm
-- LuaJIT target arm
-- Using system lua for generating dynasm via: /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua
-- Executing command: /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/dynasm/dynasm.lua -D;JIT;-D;FFI;-D;DUALNUM;-D;FPU -o /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/buildvm_arch.h /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/vm_arm.dasc
-- LUA_INCDIR: /home/erhannis/projects/torch-android/install/include
-- LUA_LIBDIR: /home/erhannis/projects/torch-android/install/lib
-- LUA_BINDIR: /home/erhannis/projects/torch-android/install/bin
-- LUALIB: /home/erhannis/projects/torch-android/install/libs/armeabi-v7a/libluajit.so
-- LUADIR: /home/erhannis/projects/torch-android/install/share/lua/5.1/
-- LIBDIR: /home/erhannis/projects/torch-android/install/lib/lua/5.1/
-- LUA_BINDIR: /home/erhannis/projects/torch-android/install/bin
-- SCRIPTS_DIR: /home/erhannis/projects/torch-android/install/bin
-- Compiling with OpenMP support
-- Compiling with OpenMP support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this on this machine.
-- No OMAP4 processor on this on this machine.
-- Atomics: using pthread
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- LAPACK requires BLAS
-- Cannot find a library with LAPACK API. Not using LAPACK.
-- C inline is supported (inline)
-- Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Compiling with OpenMP support
WARNING: Could not find JPEG libraries, JPEG wrapper will not be installed
-- Compiling with OpenMP support
-- OpenMP Found with compiler flag : -fopenmp
-- Including android directory:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/erhannis/projects/torch-android/build
 -------------- Configuring DONE ---------------
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -H/home/erhannis/projects/torch-android -B/home/erhannis/projects/torch-android/build --check-build-system CMakeFiles/Makefile.cmake 0
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/build/CMakeFiles /home/erhannis/projects/torch-android/build/distro/exe/CMakeFiles/progress.marks
cd /home/erhannis/projects/torch-android/build && make -f CMakeFiles/Makefile2 distro/exe/all
make[1]: Entering directory '/home/erhannis/projects/torch-android/build'
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/depend
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/depend
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 /home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/build
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/build
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Nothing to be done for 'distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Nothing to be done for 'distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit-static.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Nothing to be done for 'distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
[ 64%] Built target luajit-static
[ 64%] Built target libluajit
[100%] Built target luajit
make[1]: Leaving directory '/home/erhannis/projects/torch-android/build'
/usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/build/CMakeFiles 0
cd /home/erhannis/projects/torch-android/build && make -f CMakeFiles/Makefile2 distro/exe/preinstall
make[1]: Entering directory '/home/erhannis/projects/torch-android/build'
make[1]: Nothing to be done for 'distro/exe/preinstall'.
make[1]: Leaving directory '/home/erhannis/projects/torch-android/build'
Install the project...
/usr/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/luaconf.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/lua.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/lauxlib.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/lualib.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/lua.hpp
-- Up-to-date: /home/erhannis/projects/torch-android/install/include/luajit.h
-- Up-to-date: /home/erhannis/projects/torch-android/install/lib/libluajit.so
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/bc.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/v.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dump.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_x86.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_x64.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_arm.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_ppc.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_mips.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/dis_mipsel.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/bcsave.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/bc.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/p.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/zone.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/jit/vmdef.lua
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -H/home/erhannis/projects/torch-android -B/home/erhannis/projects/torch-android/build --check-build-system CMakeFiles/Makefile.cmake 0
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/build/CMakeFiles /home/erhannis/projects/torch-android/build/distro/pkg/cwrap/CMakeFiles/progress.marks
cd /home/erhannis/projects/torch-android/build && make -f CMakeFiles/Makefile2 distro/pkg/cwrap/all
make[1]: Entering directory '/home/erhannis/projects/torch-android/build'
make[1]: Nothing to be done for 'distro/pkg/cwrap/all'.
make[1]: Leaving directory '/home/erhannis/projects/torch-android/build'
/usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/build/CMakeFiles 0
cd /home/erhannis/projects/torch-android/build && make -f CMakeFiles/Makefile2 distro/pkg/cwrap/preinstall
make[1]: Entering directory '/home/erhannis/projects/torch-android/build'
make[1]: Nothing to be done for 'distro/pkg/cwrap/preinstall'.
make[1]: Leaving directory '/home/erhannis/projects/torch-android/build'
Install the project...
/usr/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/cwrap/init.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/cwrap/cinterface.lua
-- Up-to-date: /home/erhannis/projects/torch-android/install/share/lua/5.1/cwrap/types.lua
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -H/home/erhannis/projects/torch-android -B/home/erhannis/projects/torch-android/build --check-build-system CMakeFiles/Makefile.cmake 0
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_progress_start /home/erhannis/projects/torch-android/build/CMakeFiles /home/erhannis/projects/torch-android/build/distro/pkg/CMakeFiles/progress.marks
cd /home/erhannis/projects/torch-android/build && make -f CMakeFiles/Makefile2 distro/pkg/all
make[1]: Entering directory '/home/erhannis/projects/torch-android/build'
make -f distro/pkg/sundown/CMakeFiles/sundown.dir/build.make distro/pkg/sundown/CMakeFiles/sundown.dir/depend
make -f distro/pkg/paths/CMakeFiles/paths.dir/build.make distro/pkg/paths/CMakeFiles/paths.dir/depend
make -f distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/build.make distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/depend
make -f distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build.make distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/depend
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/pkg/paths /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/pkg/paths /home/erhannis/projects/torch-android/build/distro/pkg/paths/CMakeFiles/paths.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/pkg/torch/lib/luaT /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/luaT /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/pkg/sundown /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/pkg/sundown /home/erhannis/projects/torch-android/build/distro/pkg/sundown/CMakeFiles/sundown.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/pkg/paths/CMakeFiles/paths.dir/build.make distro/pkg/paths/CMakeFiles/paths.dir/build
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/build.make distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/build
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/erhannis/projects/torch-android /home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH /home/erhannis/projects/torch-android/build /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/pkg/sundown/CMakeFiles/sundown.dir/build.make distro/pkg/sundown/CMakeFiles/sundown.dir/build
[  1%] Linking C shared module ../../../../install/libs/armeabi-v7a/libpaths.so
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Nothing to be done for 'distro/pkg/torch/lib/luaT/CMakeFiles/luaT.dir/build'.
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build/distro/pkg/paths && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/paths.dir/link.txt --verbose=1
[  5%] Built target luaT
/home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -Wno-psabi --sysroot=/home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname, -o ../../../../install/libs/armeabi-v7a/libpaths.so CMakeFiles/paths.dir/paths.c.o  -L/home/erhannis/projects/torch-android/install/libs/armeabi-v7a  -L/home/erhannis/projects/torch-android/install/lib ../../../../install/libs/armeabi-v7a/libluajit.so  "/home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
make -f distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build.make distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build
/home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: -soname: must take a non-empty argument
collect2: error: ld returned 1 exit status
[  7%] Linking C shared module ../../../../install/libs/armeabi-v7a/libsundown.so
distro/pkg/paths/CMakeFiles/paths.dir/build.make:98: recipe for target '../install/libs/armeabi-v7a/libpaths.so' failed
make[2]: *** [../install/libs/armeabi-v7a/libpaths.so] Error 1
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
cd /home/erhannis/projects/torch-android/build/distro/pkg/sundown && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/sundown.dir/link.txt --verbose=1
CMakeFiles/Makefile2:396: recipe for target 'distro/pkg/paths/CMakeFiles/paths.dir/all' failed
make[1]: *** [distro/pkg/paths/CMakeFiles/paths.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -Wno-psabi --sysroot=/home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname, -o ../../../../install/libs/armeabi-v7a/libsundown.so CMakeFiles/sundown.dir/src/autolink.c.o CMakeFiles/sundown.dir/src/buffer.c.o CMakeFiles/sundown.dir/src/markdown.c.o CMakeFiles/sundown.dir/src/stack.c.o CMakeFiles/sundown.dir/html/houdini_href_e.c.o CMakeFiles/sundown.dir/html/houdini_html_e.c.o CMakeFiles/sundown.dir/html/html.c.o CMakeFiles/sundown.dir/html/html_smartypants.c.o  -L/home/erhannis/projects/torch-android/install/libs/armeabi-v7a ../../../../install/libs/armeabi-v7a/libluajit.so  "/home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
/home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: -soname: must take a non-empty argument
collect2: error: ld returned 1 exit status
make[2]: Entering directory '/home/erhannis/projects/torch-android/build'
distro/pkg/sundown/CMakeFiles/sundown.dir/build.make:280: recipe for target '../install/libs/armeabi-v7a/libsundown.so' failed
make[2]: *** [../install/libs/armeabi-v7a/libsundown.so] Error 1
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
CMakeFiles/Makefile2:323: recipe for target 'distro/pkg/sundown/CMakeFiles/sundown.dir/all' failed
make[1]: *** [distro/pkg/sundown/CMakeFiles/sundown.dir/all] Error 2
[  9%] Building C object distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THVector.c.o
cd /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH && /home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -DANDROID -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DTH_EXPORTS -DTH_GENERIC_USE_HALF=1 -DUSE_PTHREAD_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -isystem /home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm/usr/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/erhannis/projects/torch-android/install/include -I/home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src -I/home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 -I/home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH -I/home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH -I/home/erhannis/projects/torch-android/distro/pkg/torch/lib/luaT -I/home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/luaT  -Wno-psabi --sysroot=/home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -Werror=implicit-function-declaration -Werror=format -fopenmp -fopenmp -DTH_HAVE_THREAD -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG -fPIC   -o CMakeFiles/TH.dir/THVector.c.o   -c /home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/THVector.c
In file included from /home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/THVector.c:3:0:
/home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/generic/THVectorDispatch.c: In function 'THByteVector_vectorDispatchInit':
/home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^
/home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build.make:377: recipe for target 'distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THVector.c.o' failed
make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THVector.c.o] Error 1
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
CMakeFiles/Makefile2:530: recipe for target 'distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all' failed
make[1]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all] Error 2
make[1]: Leaving directory '/home/erhannis/projects/torch-android/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by p-tricky** [comment]
Same issue for me.  I think it might be related to [this](https://github.com/torch/torch7/issues/762)

**Comment by borisfom** [comment]
Yes you need Android NDK 13b and extra flags.
I have pushed changes to build.sh and added a note to README.
@soumith: you may want to push this update to soumith/torch-android repo!

**Comment by BrianOn99** [comment]
@borisfom Thanks for the the quick response, there is no problem for FindCUDA now, but the `impossible constraint in 'asm'` still exists after I fresh git clone this repo, and downloaded Android NDK 13b from the link in README:

```
[ 55%] Building C object distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THVector.c.o
cd /home/o/proj/torch-android/build/distro/pkg/torch/lib/TH && /home/o/Android/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -DANDROID -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DTH_EXPORTS -DTH_GENERIC_USE_HALF=1 -DUSE_PTHREAD_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -Wno-psabi --sysroot=/home/o/Android/android-ndk-r13b/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -Werror=implicit-function-declaration -Werror=format -fopenmp -fopenmp -DTH_HAVE_THREAD -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG -fPIC -isystem /home/o/Android/android-ndk-r13b/platforms/android-21/arch-arm/usr/include -isystem /home/o/Android/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/o/Android/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /home/o/Android/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/o/proj/torch-android/install/include -I/home/o/proj/torch-android/distro/exe/luajit-rocks/luajit-2.1/src -I/home/o/proj/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 -I/home/o/proj/torch-android/distro/pkg/torch/lib/TH -I/home/o/proj/torch-android/build/distro/pkg/torch/lib/TH -I/home/o/proj/torch-android/distro/pkg/torch/lib/luaT -I/home/o/proj/torch-android/build/distro/pkg/torch/lib/luaT    -o CMakeFiles/TH.dir/THVector.c.o   -c /home/o/proj/torch-android/distro/pkg/torch/lib/TH/THVector.c
In file included from /home/o/proj/torch-android/distro/pkg/torch/lib/TH/THVector.c:3:0:
/home/o/proj/torch-android/distro/pkg/torch/lib/TH/generic/THVectorDispatch.c: In function 'THByteVector_vectorDispatchInit':
/home/o/proj/torch-android/distro/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^
/home/o/proj/torch-android/distro/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build.make:358: distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THVector.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....

make[2]: Leaving directory '/home/o/proj/torch-android/build'
make[1]: *** [CMakeFiles/Makefile2:479: distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all] Error 2
make[1]: Leaving directory '/home/o/proj/torch-android/build'
make: *** [Makefile:121: all] Error 2
```

As you can see, I am using `android-ndk-r13b`
Am I missing something? Thanks in advance

**Comment by BrianOn99** [comment]
Forgot to say that I have turned OFF cuda

**Comment by Erhannis** [comment]
It seems like there's a missing `cd $SCRIPT_ROOT_DIR` before line 120 of the build.sh

**Comment by BrianOn99** [comment]
@Erhannis Do you manage to build the samples with your modification?

**Comment by Erhannis** [comment]
Nope.  Still get asm error.  As p-tricky mentions, it's probably this issue: https://github.com/torch/torch7/issues/762

**Comment by BrianOn99** [comment]
OK. Thanks for your information.

**Comment by Erhannis** [comment]
Note to observers: @borisfom mentioned "Please use https://NVIDIA/torch-android.git in the meantime."  I think he meant https://github.com/NVIDIA/torch-distro.git - it hasn't helped me, though, as the version of that referenced as a submodule of torch-android is broken, and the last couple commits of NVIDIA/torch-distro refer to a private (?) https://github.com/NVIDIA/torch-cudnn-pvt.git , so I can't actually build the most recent version of https://github.com/NVIDIA/torch-distro.git
